package render

import (
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/balyakin/crawlledger/internal/domain"
)

type caddyRenderer struct{}

func (caddyRenderer) Target() string { return "caddy" }

func (caddyRenderer) Validate(input Input) error {
	if err := validateCommon(input); err != nil {
		return err
	}
	for _, rule := range input.Policy.Rules {
		if rule.Action.Kind != domain.ActionAllow && rule.Action.Kind != domain.ActionDeny {
			return errors.New("Caddy supports only allow and deny")
		}
	}
	return nil
}

func (caddyRenderer) Render(input Input) ([]Artifact, error) {
	if err := (caddyRenderer{}).Validate(input); err != nil {
		return nil, err
	}
	var output strings.Builder
	output.WriteString("# Generated by CrawlLedger 1.0.0; import before reverse_proxy.\n")
	output.WriteString("map {http.request.header.User-Agent} {crawlledger_crawler} {\n")
	for _, entry := range input.Catalog.Entries() {
		expression := "(?i)(?:^|[ /;()+])" + regexp.QuoteMeta(entry.Token) + "(?:$|[ /;()+])"
		fmt.Fprintf(&output, "\t%s %s\n", strconv.Quote("~"+expression), strconv.Quote(entry.Name))
	}
	output.WriteString("\tdefault \"\"\n}\n\nroute {\n")
	for _, rule := range input.Policy.Rules {
		name := "crawlledger_" + strings.ReplaceAll(rule.ID, "-", "_")
		fmt.Fprintf(&output, "\t@%s {\n", name)
		if len(rule.Match.Methods) > 0 {
			fmt.Fprintf(&output, "\t\tmethod %s\n", strings.Join(rule.Match.Methods, " "))
		}
		names := expandedNames(rule, input.Catalog)
		if len(names) > 0 {
			quoted := make([]string, len(names))
			for index, crawler := range names {
				quoted[index] = strconv.Quote(crawler)
			}
			fmt.Fprintf(&output, "\t\tvars {crawlledger_crawler} %s\n", strings.Join(quoted, " "))
		}
		if len(rule.Match.PathPrefixes) > 0 {
			parts := make([]string, len(rule.Match.PathPrefixes))
			for index, path := range rule.Match.PathPrefixes {
				if path == "/" {
					parts[index] = "^/"
				} else {
					parts[index] = "^" + regexp.QuoteMeta(strings.TrimSuffix(path, "/")) + "(?:/|$)"
				}
			}
			fmt.Fprintf(&output, "\t\tpath_regexp %s_path %s\n", name, strconv.Quote("(?:"+strings.Join(parts, "|")+")"))
		}
		output.WriteString("\t}\n")
		fmt.Fprintf(&output, "\thandle @%s {\n", name)
		if rule.Action.Kind == domain.ActionDeny {
			output.WriteString("\t\trespond \"Forbidden\" 403\n")
		} else {
			output.WriteString("\t\tvars crawlledger_policy allow\n")
		}
		output.WriteString("\t}\n\n")
	}
	output.WriteString("\thandle {\n\t\tvars crawlledger_policy default\n\t}\n}\n")
	artifacts := []Artifact{{Name: "Caddyfile.crawlledger", Content: []byte(output.String())}}
	if err := validateArtifacts(artifacts); err != nil {
		return nil, err
	}
	return artifacts, nil
}
