package render

import (
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/balyakin/crawlledger/internal/catalog"
	"github.com/balyakin/crawlledger/internal/domain"
)

type nginxRenderer struct{}

func (nginxRenderer) Target() string { return "nginx" }

func (nginxRenderer) Validate(input Input) error {
	if err := validateCommon(input); err != nil {
		return err
	}
	for _, rule := range input.Policy.Rules {
		if rule.Action.Kind == domain.ActionCache {
			return errors.New("cache action cannot be rendered")
		}
	}
	if matcherClauses(input.Policy, input.Catalog) > 200 {
		return errors.New("Nginx matcher clause cap exceeded")
	}
	for _, states := range input.ObservedStates {
		if zoneMiB(states) > 256 {
			return errors.New("Nginx rate zone exceeds 256 MiB")
		}
	}
	return nil
}

func (nginxRenderer) Render(input Input) ([]Artifact, error) {
	if err := (nginxRenderer{}).Validate(input); err != nil {
		return nil, err
	}
	shortHash := input.Simulation.PolicyHash[:8]
	var http strings.Builder
	fmt.Fprintf(&http, "# Generated by CrawlLedger 1.0.0; policy sha256: %s\n", input.Simulation.PolicyHash)
	fmt.Fprintf(&http, "map $http_user_agent $crawlledger_%s_crawler {\n    default \"\";\n", shortHash)
	for _, entry := range input.Catalog.Entries() {
		expression := `~*(?:^|[ /;()+])` + regexp.QuoteMeta(entry.Token) + `(?:$|[ /;()+])`
		fmt.Fprintf(&http, "    \"%s\" \"%s\";\n", nginxQuote(expression), nginxQuote(entry.Name))
	}
	http.WriteString("}\n\n")
	fmt.Fprintf(&http, "map \"$request_method|$crawlledger_%s_crawler|$uri\" $crawlledger_%s_action {\n    default \"allow\";\n", shortHash, shortHash)
	lines := 0
	profiles := make(map[string]struct{})
	for _, rule := range input.Policy.Rules {
		names := expandedNames(rule, input.Catalog)
		methods := rule.Match.Methods
		paths := rule.Match.PathPrefixes
		if len(names) == 0 {
			names = []string{""}
		}
		if len(methods) == 0 {
			methods = []string{""}
		}
		if len(paths) == 0 {
			paths = []string{""}
		}
		for _, method := range methods {
			for _, name := range names {
				for _, path := range paths {
					lines++
					if lines > 200 {
						return nil, errors.New("Nginx matcher clause cap exceeded")
					}
					expression := compositeExpression(method, name, path)
					action := string(rule.Action.Kind)
					if rule.Action.Kind == domain.ActionRateLimit {
						action = "rate_" + *rule.Action.RateProfile
						profiles[*rule.Action.RateProfile] = struct{}{}
					}
					fmt.Fprintf(&http, "    \"%s\" \"%s\";\n", nginxQuote("~"+expression), action)
				}
			}
		}
	}
	http.WriteString("}\n\n")
	profileNames := sortedKeys(profiles)
	for _, profile := range profileNames {
		rate, _ := profileValues(profile)
		fmt.Fprintf(&http, "map $crawlledger_%s_action $crawlledger_%s_%s_key {\n", shortHash, shortHash, profile)
		fmt.Fprintf(&http, "    default \"\";\n    \"rate_%s\" \"$binary_remote_addr:$crawlledger_%s_crawler\";\n}\n", profile, shortHash)
		fmt.Fprintf(&http, "limit_req_zone $crawlledger_%s_%s_key zone=crawlledger_%s_%s:%dm rate=%dr/m;\n\n",
			shortHash, profile, shortHash, profile, zoneMiB(input.ObservedStates[profile]), rate)
	}
	var server strings.Builder
	server.WriteString("# Include inside the audited server block before the content handler.\n")
	hasDeny := false
	for _, rule := range input.Policy.Rules {
		hasDeny = hasDeny || rule.Action.Kind == domain.ActionDeny
	}
	if hasDeny {
		fmt.Fprintf(&server, "if ($crawlledger_%s_action = deny) { return 403; }\n", shortHash)
	}
	if len(profileNames) > 0 {
		server.WriteString("limit_req_status 429;\n")
	}
	for _, profile := range profileNames {
		_, burst := profileValues(profile)
		fmt.Fprintf(&server, "limit_req zone=crawlledger_%s_%s burst=%d nodelay;\n", shortHash, profile, burst)
	}
	artifacts := []Artifact{
		{Name: "crawlledger-http.conf", Content: []byte(http.String())},
		{Name: "crawlledger-server.conf", Content: []byte(server.String())},
	}
	if err := validateArtifacts(artifacts); err != nil {
		return nil, err
	}
	return artifacts, nil
}

func expandedNames(rule domain.PolicyRule, catalogValue *catalog.Catalog) []string {
	names := append([]string(nil), rule.Match.CrawlerNames...)
	for _, category := range rule.Match.Categories {
		for _, entry := range catalogValue.EntriesByCategory(category) {
			names = append(names, entry.Name)
		}
	}
	sort.Strings(names)
	result := names[:0]
	for _, name := range names {
		if len(result) == 0 || result[len(result)-1] != name {
			result = append(result, name)
		}
	}
	return result
}

func compositeExpression(method, crawler, path string) string {
	methodExpression := `[A-Z0-9_-]+`
	if method != "" {
		methodExpression = regexp.QuoteMeta(method)
	}
	crawlerExpression := `[^|]*`
	if crawler != "" {
		crawlerExpression = regexp.QuoteMeta(crawler)
	}
	pathExpression := `.*`
	if path != "" {
		if path == "/" {
			pathExpression = `/.*`
		} else {
			pathExpression = regexp.QuoteMeta(strings.TrimSuffix(path, "/")) + `(?:/|$).*`
		}
	}
	return "^" + methodExpression + `\|` + crawlerExpression + `\|` + pathExpression + "$"
}

func matcherClauses(value domain.Policy, catalogValue *catalog.Catalog) int {
	total := 0
	for _, rule := range value.Rules {
		names, methods, paths := len(expandedNames(rule, catalogValue)), len(rule.Match.Methods), len(rule.Match.PathPrefixes)
		if names == 0 {
			names = 1
		}
		if methods == 0 {
			methods = 1
		}
		if paths == 0 {
			paths = 1
		}
		total += names * methods * paths
	}
	return total
}

func nginxQuote(value string) string {
	return strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`).Replace(value)
}

func profileValues(profile string) (int, int) {
	switch profile {
	case "gentle":
		return 60, 20
	case "standard":
		return 30, 10
	default:
		return 10, 5
	}
}

func zoneMiB(states int64) int64 {
	bytes := states * 256 * 2
	value := (bytes + (1 << 20) - 1) / (1 << 20)
	if value < 1 {
		return 1
	}
	return value
}

func sortedKeys(values map[string]struct{}) []string {
	result := make([]string, 0, len(values))
	for value := range values {
		result = append(result, value)
	}
	sort.Strings(result)
	return result
}
